### ISSUE TITLE
I have an issue with everything

### ISSUE THREAD

**Issue by creativeoneteam** [neogeek/dotfiles#1]
Love Chris

**Comment by neogeek** [comment]
![](https://media.giphy.com/media/6RoUMn34pqvcs/giphy.gif)

**Comment by neogeek** [comment]
Oddly enough I think I might have fixed the [NPM] issue you were having that caused this incredible detailed bug report.

See https://github.com/neogeek/dotfiles/commit/e10dec547e39cab139aee45e233c98e8e062a928 for more information.

**Comment by creativeoneteam** [comment]
that's stupid
